"""
Defines the error message and error code
"""
ASYNCMESSAGINGQUEUE_ERROR_PEEK_NOT_SUPPORTED = 3003
ASYNCMESSAGINGQUEUE_ERROR_INVALID_ITEM_ENQUEUED = 3004
ASYNCMESSAGINGQUEUE_ERROR_SETRESULT_INVOKED_WITH_INVALID_ID = 3005
ASYNCMESSAGINGQUEUE_ERROR_SETRESULT_NOT_SUPPORTED = 3006
ASYNCMESSAGINGQUEUE_ERROR_WHILE_SETTING_UP_BACKEND = 3007

AsyncMessagingQueueErrorMessages = {
    ASYNCMESSAGINGQUEUE_ERROR_PEEK_NOT_SUPPORTED: 'Peek operation is not supported on this queue',
    ASYNCMESSAGINGQUEUE_ERROR_INVALID_ITEM_ENQUEUED: 'Async Queue can accept items of type AsyncTaskSpec Only',
    ASYNCMESSAGINGQUEUE_ERROR_SETRESULT_INVOKED_WITH_INVALID_ID: 'Set result invoked with invalid id. Details : {0}',
    ASYNCMESSAGINGQUEUE_ERROR_SETRESULT_NOT_SUPPORTED: 'Set result not supported on queue. Details : {0}',
    ASYNCMESSAGINGQUEUE_ERROR_WHILE_SETTING_UP_BACKEND: 'Error while setting up backend. Details : {0}'
}
